### ISSUE TITLE
Integration with egui

### ISSUE THREAD

**Issue by rsaccon** [ricosjp/truck#18]
I like very much the direction truck is going and as very early adaptor I am trying to integrate it with [egui](https://github.com/emilk/eguil). Truck has a nice wgpu integration and for egui there is also a [wgpu integration example](https://github.com/hasenbanck/egui_example). So I would like to use egui for all the app initialization and event handling and truck just for rendering a truck scene. 

Now I took a look at [truck-js](https://github.com/ricosjp/truck/blob/master/truck-js/examples/script.js) to get an idea for the most bare bone approach, turning a Polygon mesh into a buffer suitable for webGL. However I would like to reuse as much as possible from truck wpgu [render implementation](https://github.com/ricosjp/truck/tree/master/truck-rendimpl). I think the examples and also what is in the [tests folder](https://github.com/ricosjp/truck/tree/master/truck-rendimpl/tests) is important for my use case. However I feel a bit lost right now ...

So my questions are:
- is there any plan to support any particular GUI libraries ?
- in case you are familiar with egui, do you have any advice ?
- does it make sense, just to get from the truck scene a low level wgpu object which I render somehow just before egui does its rendering ?

**Comment by rsaccon** [comment]
While waiting for your advice, I tried myself to come up with something. So here what I did: I used the truck app framework as base and just added the egui rendering as part of the `app.render()` implementation. Here is how it looks like:
``` Rust
    // This method is called every frame.
    fn render(&mut self) {
        // truck
        self.scene.render_frame();  // with `surface_texture.present();` commented out

        // egui
        let frame = self
            .scene
            .window_handler  // had to make public
            .surface  // had to make public
            .get_current_texture()
            .unwrap();
        let target = frame
            .texture
            .create_view(&wgpu::TextureViewDescriptor::default());
        let mut encoder =
            self.scene
                .device()
                .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                    label: Some("Render Encoder"),
                });
        let surface_config = &self
            .scene
            .scene_desc  // had to make public
            .render_texture
            .compatible_surface_config();

        self.egui_renderer.render(
            &self.scene.device(),
            &self.scene.device_handler().queue(),
            &mut encoder,
            &target,
            &mut self.gui,
            self.scene.window_handler.window.scale_factor(),
            surface_config,
        );

        // Submit the command buffer to the queue to run everything.
        let _ = &self.scene.queue().submit(Some(encoder.finish()));
        frame.present();
    }
```
As you see in the code comments above, I had to make public several private members and sub-members of `WindowScene`. And in the original `Scene::render_frame` code I had to comment out the last line (`surface_texture.present();`) and then call it explicitly after I had done all the egui rendering steps. The egui stuff itself is based on [egui_wgpu_backend](https://github.com/hasenbanck/egui_wgpu_backend) and for `egui_renderer` I am using a little helper which I more or less just copy-pasted from the [ennoa project](https://github.com/rust-cv/ennona/blob/main/src/state/gui_renderer.rs). And I had to slightly modify the truck app framework, in order to possibly handle first any events from egui.

To sum up: with this approach I got egui  and truck rendering in the same app, but unfortunately I run into a borrow checker issue when I tried to make the scene accessible from the egui app. And on my mac it horribly leaks memory. After a few minutes the app panics. But that is (hopefully) just related to a mac-specific wgpu issue (which has been fixed on the wgpu master branch already)

Now my questions are:
- Do you have any suggestion for a different approach where `WindowScene` does not need to be modified ?
- What about an alternative truck app framework which has the egui integration already baked in ?  I was thinking of just merging the relevant parts of the [wgpu-egui-demo-app](https://github.com/hasenbanck/egui_example/blob/master/src/main.rs) with the truck app framework. I will probably try that next ...

**Comment by ytanimura** [comment]
The `app` framework in truck's examples has been left out of the package for modification. Please feel free to modify it.  
We certainly need a methods to get `Window` and `Surface` references from `WindowScene`. We'll implement that.  
The field `scene_desc` of `Scene` can be referenced using the method `Scene::descriptor`. Please use it.  

Now, about `render_frame`, this method consists of three steps:
1. Make sure the size of the depth buffer etc. matches the size of the window.
2. Get the current texture of the surface.
3. Draw on the current texture.
4. Present the current texture.

Since the implementation for egui is done in step 2, I think the problem can be solved by creating a public method that does step 1.

We'll implement it today, Japan time.

**Comment by ytanimura** [comment]
Now some new methods implemented. Please try to use the following code.

```rust
    // This method is called every frame.
    fn render(&mut self) {
        let frame = self
            .scene
            .surface()
            .get_current_texture()
            .unwrap();
        let target = frame
            .texture
            .create_view(&wgpu::TextureViewDescriptor::default());

        // truck
        self.scene.size_alignment();
        self.scene.render(&target);

        // egui
        let mut encoder =
            self.scene
                .device()
                .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                    label: Some("Render Encoder"),
                });
        let surface_config = &self
            .scene
            .descriptor()
            .render_texture
            .compatible_surface_config();

        self.egui_renderer.render(
            &self.scene.device(),
            &self.scene.queue(),
            &mut encoder,
            &target,
            &mut self.gui,
            self.scene.window().scale_factor(),
            surface_config,
        );

        // Submit the command buffer to the queue to run everything.
        let _ = &self.scene.queue().submit(Some(encoder.finish()));
        frame.present();
    }
```

**Comment by rsaccon** [comment]
Ok, thanks a lot, tried it, unfortunately compiler complained and I (don't fully understand why, but I) had again to make private members public in truck source. 

in platform lib.rs

``` Rust
#[derive(Debug)]
struct WindowHandler {
pub struct WindowHandler {
    window: Arc<winit::window::Window>,
    pub surface: Arc<Surface>, // HERE
}

/// The unique ID for `Rendered` struct.
pub struct WindowScene {
    #[deref]
    #[deref_mut]
    scene: Scene,
    pub window_handler: WindowHandler, // HERE
}
```
and in platform Scene.rs:
``` Rust
impl RenderTextureConfig {
    pub fn compatible_surface_config(self) -> SurfaceConfiguration {  // HERE
        SurfaceConfiguration {
            usage: TextureUsages::RENDER_ATTACHMENT,
            format: self.format,
```

**Comment by rsaccon** [comment]
Ups, mistake on my side, the private members I accessed from somewhere else, so ONLY the `compatible_surface_config` which still needs to be made public.

**Comment by ytanimura** [comment]
OK. Now, `compatible_surface_config` is public in master branch!

**Comment by ytanimura** [comment]
We remark that this method must be called after `size_alignment`. Otherwise, the panic occurs caused by the mismatch between the surface size and the window one.

**Comment by rsaccon** [comment]
@ytanimura thanks to your help, now the egui integration works fine. I still have issues with my demo example but they are caused by my code, not by egui or truck. So I am gonna close this ticket.
