### ISSUE TITLE
How to update WireFrameInstance ?

### ISSUE THREAD

**Issue by rsaccon** [ricosjp/truck#25]
for updating the mesh at a `PolygonInstance`  I do:

`my_polygon_instance.swap_vertex(&mut another_polygon_instance);` 

for updating the vertices and indexes of a `WireFrameInstance` there is no such equivalent.  I tried to do it myself with something like:
```
my_wire_instance.vertices = another_wire_instance.vertices.clone();
my_wire_instance.strips = another_wire_instance.strips.clone();
```
but that is not possible, because the `vertices` and `strips` are private.

Am I missing something ?

**Comment by ytanimura** [comment]
Thank you for your issue. Certainly, there is not such a method. We will add it. Please wait a little.

**Comment by ytanimura** [comment]
Now added the method. https://github.com/ricosjp/truck/blob/master/truck-rendimpl/src/wireframe_instance.rs#L33

**Comment by rsaccon** [comment]
Great, thanks.
