### ISSUE TITLE
Step file with circle can't be triangulated

### ISSUE THREAD

**Issue by happydpc** [ricosjp/truck#41]
If there's some circle curve, the UnitCircle with Processor can't be tessellated.  May be the polyline is just unit circle polyline, without being transformed by processor's transform.
 
Here is the test file:
[example_step.zip](https://github.com/ricosjp/truck/files/10834640/example_step.zip)

**Comment by ytanimura** [comment]
Thank you for your issue. We have implemented only the parse so far first, but we was just about to implement a test for the entire geometry now. This bug should be fixed by the end of March.

**Comment by ytanimura** [comment]
It has been a long time since March, but we are now able to do meshing this data!
