### ISSUE TITLE
Volume, Center of Mass

### ISSUE THREAD

**Issue by MattFerraro** [ricosjp/truck#56]
Hello,

Would it be possible to implement something like `solid::volume()` and `solid::center_of_mass()`? These are very useful for CAD applications.

Cheers

**Comment by ytanimura** [comment]
Thank you for your comment.

We added implementation to calculate the volume and the center of gravity of `PolygonMesh` and `Solid<Point3, PolylineCurve<Point3>, PolygonMesh>`.

implementation: https://github.com/ricosjp/truck/blob/master/truck-meshalgo/src/analyzers/volume.rs
test (sample code): https://github.com/ricosjp/truck/blob/master/truck-meshalgo/tests/analyzers/volume.rs#L17

**Comment by MattFerraro** [comment]
Excellent, thank you!
