### ISSUE TITLE
truck-meshalgo depends on soon-to-be incompatible crate version

### ISSUE THREAD

**Issue by dzervas** [ricosjp/truck#72]
truck-meshalgo depends on vtkio 0.6 which in turn depends on nom v3.2.1 and quick-xml v0.22.0

Both of these dependencies are reported as future-incompatibilities

Updating to vtkio 0.7 will fix both deps

**Comment by ytanimura** [comment]
Yeah, we are aware of this. I hope `vtkio` will be updated, as there is no immediate solution we can take...
