### ISSUE TITLE
Future compatibility warning due to outdated dependencies

### ISSUE THREAD

**Issue by elgar328** [ricosjp/truck#83]
When compiling an example from this library, the following warning was displayed:

```
warning: the following packages contain code that will be rejected by a future version of Rust: nom v3.2.1, quick-xml v0.22.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
```

It seems that some dependencies of this library are outdated and may become incompatible with future versions of Rust.

Upon checking crates.io, I found that the following dependencies used in this library are outdated:
	•	quick-xml: Currently at v0.22.0, but the latest version is v0.37.1.
	•	nom: Currently at v3.2.1, but the latest version is v7.1.3.
These older versions may contain code that is incompatible with newer versions of Rust.

**Comment by ytanimura** [comment]
This is a topic that was discussed in #72. In some cases, it may be necessary to stop vtk I/O for a while. There is nothing we can do about it, so we can only pray.
